# Generated by Django 5.0.1 on 2024-01-14 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daniapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_name', models.CharField(max_length=100)),
                ('established', models.BooleanField(default=False)),
            ],
        ),
    ]
