# Generated by Django 5.0.1 on 2024-01-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daniapp', '0002_broker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=100)),
            ],
        ),
    ]
