# Generated by Django 5.0.1 on 2024-02-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daniapp', '0003_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='seller_established',
            field=models.BooleanField(default=False),
        ),
    ]
