# Generated by Django 5.0.1 on 2024-02-09 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daniapp', '0004_seller_seller_established'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='startdate',
            field=models.DateField(default=datetime.time),
        ),
    ]
