# Generated by Django 5.0.1 on 2024-02-09 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daniapp', '0005_seller_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='startdate',
            field=models.DateField(default="<class 'datetime.time'>"),
        ),
    ]
