# Generated by Django 5.0.1 on 2024-02-09 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daniapp', '0007_alter_seller_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='startdate',
            field=models.DateField(default=datetime.datetime(2024, 2, 9, 2, 10, 53, 749066, tzinfo=datetime.timezone.utc)),
        ),
    ]
