# Generated by Django 5.0.1 on 2024-02-09 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daniapp', '0008_alter_seller_startdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='startdate',
        ),
    ]
